#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias et='emacsclient -t'
alias ec='emacsclient -c'
alias eck="emacsclient -e '(kill-emacs)'"
alias be='bundle exec'
if $(type bat &> /dev/null); then
  alias cat=$(command -v bat)
fi
if $(type batcat &> /dev/null); then
  alias cat=$(command -v batcat)
fi

# Allow kill word and moving forward/backword by word to behave like
# bash (e.g. stop at / chars)
# autoload -U select-word-style
# select-word-style bash

# if ! [ -n "$(pgrep gpg-agent)" ]; then eval $(gpg-agent --daemon); fi

export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.nodenv/bin:$PATH"
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
export TERM="screen-256color"

if command -v rbenv 1>/dev/null 2>&1; then
   eval "$(rbenv init -)"
fi

if command -v nodenv 1>/dev/null 2>&1; then
   eval "$(nodenv init -)"
fi

# if command -v pyenv 1>/dev/null 2>&1; then
#    eval "$(pyenv init -)"
# fi
